name: reviewdog
on: [push, pull_request]
jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-check
        uses: tsuyoshicho/action-textlint@v1
        if: github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          textlint_flags: "articles/*.md books/*.md"
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v1
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          textlint_flags: "articles/*.md books/*.md"
