name: reviewdog
on: [push, pull_request]
jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: textlint-github-check article
        uses: tsuyoshicho/action-textlint@v1
        if: github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: info
          textlint_flags: "articles/**"
      - name: textlint-github-check book
        uses: tsuyoshicho/action-textlint@v1
        if: github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: info
          textlint_flags: "books/**"
      - name: textlint-github-pr-review article
        uses: tsuyoshicho/action-textlint@v1
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          reporter: github-pr-review
          level: info
          textlint_flags: "articles/**"
      - name: textlint-github-pr-review book
        uses: tsuyoshicho/action-textlint@v1
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          reporter: github-pr-review
          level: info
          textlint_flags: "books/**"
